name: flutternaut
description: "A concise Semantics wrapper for Flutter test automation. Provides named constructors for common UI patterns (buttons, inputs, text, list items, checkboxes)."
version: 0.0.3
homepage: https://flutternaut.app
repository: https://github.com/KhaledMoSha/flutternaut
resolution: workspace

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutternaut_generator: ^0.0.2
  # flutternaut_generator:
  #   path: ../flutternaut_generator

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

executables:
  flutternaut: flutternaut
