name: flutternaut_example
description: Example app demonstrating Flutternaut widgets and view annotations.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutternaut:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutternaut_generator: ^0.0.2

flutter:
  uses-material-design: true
